# Generated by Django 3.2 on 2023-01-04 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ven_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ven', unique=True)),
                ('ven_title', models.CharField(default='Nestify', max_length=100)),
                ('ven_image', models.ImageField(default='vendor.jpg', upload_to='user_directory_path')),
                ('ven_description', models.TextField(blank=True, default='I am a great vendor', null=True)),
                ('ven_address', models.CharField(default='123 Main Street', max_length=100)),
                ('ven_contact', models.CharField(default='+123 (456) 789', max_length=100)),
                ('ven_chat_response_time', models.CharField(default='100', max_length=100)),
                ('ven_shipping_on_time', models.CharField(default='100', max_length=100)),
                ('ven_authentic_rating', models.CharField(default='100', max_length=100)),
                ('ven_days_return', models.CharField(default='100', max_length=100)),
                ('ven_warranty_period', models.CharField(default='100', max_length=100)),
                ('ven_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
