# Generated by Django 3.2 on 2023-01-04 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='prod', unique=True)),
                ('prod_title', models.CharField(default='Fresh pear', max_length=100)),
                ('prod_image', models.ImageField(default='product.jpg', upload_to='user_directory_path')),
                ('prod_description', models.TextField(blank=True, default='This is the product', null=True)),
                ('prod_new_price', models.DecimalField(decimal_places=2, default='1.99', max_digits=100)),
                ('prod_old_price', models.DecimalField(decimal_places=2, default='2.99', max_digits=100)),
                ('pro_specifications', models.TextField(blank=True, null=True)),
                ('pro_status_choice', models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In_review'), ('published', 'Published')], default='in_review', max_length=10)),
                ('prod_status', models.BooleanField(default=True)),
                ('prod_in_stock', models.BooleanField(default=True)),
                ('prod_featured', models.BooleanField(default=False)),
                ('prod_digital', models.BooleanField(default=False)),
                ('prod_sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='sku', unique=True)),
                ('prod_created', models.DateTimeField(auto_now_add=True)),
                ('prod_updated', models.DateTimeField(blank=True, null=True)),
                ('prod_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('prod_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag')),
                ('prod_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
