# Generated by Django 3.2 on 2023-01-04 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cartorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoritem_invoice_number', models.CharField(max_length=200)),
                ('cartoritem_status', models.CharField(max_length=200)),
                ('cartoritem_item', models.CharField(max_length=200)),
                ('cartoritem_image', models.CharField(max_length=200)),
                ('cartoritem_quantity', models.ImageField(default=0, upload_to='')),
                ('cartoritem_price', models.DecimalField(decimal_places=2, default='1.99', max_digits=100)),
                ('cartoritem_total_price', models.DecimalField(decimal_places=2, default='1.99', max_digits=100)),
                ('cartoritem_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartorder')),
            ],
            options={
                'verbose_name_plural': 'Cart order items',
            },
        ),
    ]
