# Generated by Django 3.2 on 2023-01-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_digital',
            new_name='digital',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_featured',
            new_name='featured',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_in_stock',
            new_name='in_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_new_price',
            new_name='new_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_old_price',
            new_name='old_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_id',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_sku',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pro_specifications',
            new_name='specifications',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_tag',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_user',
            new_name='user',
        ),
    ]
