# Generated by Django 3.2 on 2023-01-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230104_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_title',
            new_name='title',
        ),
    ]
