# Generated by Django 3.2 on 2023-01-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230104_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_authentic_rating',
            new_name='authentic_rating',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_chat_response_time',
            new_name='chat_response_time',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_days_return',
            new_name='days_return',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_shipping_on_time',
            new_name='shipping_on_time',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_id',
            new_name='vid',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ven_warranty_period',
            new_name='warranty_period',
        ),
    ]
