# Generated by Django 3.2 on 2023-01-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230104_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='prodim_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='prodim_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='prodim_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='prodim_updated',
            new_name='updated',
        ),
    ]
