# Generated by Django 3.2 on 2023-01-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230104_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='cartor_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='cartor_paid_status',
            new_name='paid_status',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='cartor_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='cartor_process_status',
            new_name='process_status',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='cartor_user',
            new_name='user',
        ),
    ]
