# Generated by Django 3.2 on 2023-01-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230104_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='cartoritem_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='cartoritem_invoice_number',
            new_name='invoice_number',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='cartoritem_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='cartoritem_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='cartoritem_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='cartoritem_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='cartoritem_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='cartoritem_total_price',
            new_name='total_price',
        ),
    ]
