# Generated by Django 3.2 on 2023-01-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230104_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='prod_image',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='prodrev_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='prodrev_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='prodrev_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='prodrev_review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='prodrev_user',
            new_name='user',
        ),
    ]
