# Generated by Django 3.2 on 2023-01-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
