# Generated by Django 3.2 on 2023-01-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230104_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pro_status_choice',
            new_name='status_choice',
        ),
    ]
