# Generated by Django 4.0 on 2023-01-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_stock_product_stock_status_alter_product_life'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_status',
            new_name='stock_count',
        ),
    ]
