# Generated by Django 4.0 on 2023-01-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_stock_status_product_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image_hover',
            field=models.ImageField(default='product.jpg', upload_to='user_directory_path'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status_choice',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In_review'), ('published', 'Published')], default='in_review', max_length=10, verbose_name='Product status'),
        ),
    ]
